se agrega funcionalidad para traer los proyectos, se agregan clases c…
ciceunicen/web pull request #4
Opened 2022-12-29 05:40 UTC by rociocpoppe

…ss para visualización de la tabla

2022-12-29 13:22 UTC, IvanSamudio requested changes
Falta agregar paginado

2023-01-02 22:56 UTC, 01Marina requested changes
En el páginado hay comportamiento inadecuado, cuando se llega a la ultima o unica página no se deberia poder pasar a una siguiente página, no hay más registros que mostrar.

2023-01-03 14:53 UTC, IvanSamudio approved these changes

2023-01-03 15:52 UTC, 01Marina approved these changes

2023-01-03 15:53 UTC, merged