Cicedev 232
ciceunicen/web pull request #75
Opened 2024-05-30 19:30 UTC by scianca1

Anteriormente tenia un "Solicitar turno",  lo elimine, agrege un mensaje de bienvenida personalizado con el nombre del usuario y el logo del cice centrado en el header

2024-06-04 14:22 UTC, ciceunicen requested changes
Cuando estas logueado con un usuario con rol emprendedor, quedan mal las notificaciones. En la imagen se ve como quedan pegados el logo del CICE con la campanita de las notificaciones. 
Fijate de resolverlo y que queden bien separados como en las otras pantallas, la campanita de notificaciones a la derecha de la pantalla. 

![Screenshot_1](https://github.com/ciceunicen/web/assets/118905050/c73d9990-0f0e-4de8-8e3f-c786feaff6f4)

2024-06-04 23:52 UTC, ciceunicen approved these changes

2024-06-05 17:59 UTC, Renzo-Guerra approved these changes

2024-06-05 18:01 UTC, Renzo-Guerra commented
Algo que me inquieta un poco es que el header en si está todo con margenes fijos, en vez de utilizar propiedades de css para que se vaya adaptando (entiendo que por el momento no hay que hacerlo responsive, pero cuando hagan la parte de responsive para celular van a tener que modificar mas cosas)

2024-06-06 19:51 UTC, merged