Cicedev 233
ciceunicen/web pull request #78
Opened 2024-06-06 20:04 UTC by scianca1

Se creó la sección para los usuarios superAdmin en la que van a poder aceptar solicitudes de usuarios por defecto que quieran ser emprendedores. En la misma, van a poder deshacer los cambios siempre y cuando no se recargue nuevamente la página.

2024-06-07 14:45 UTC, ciceunicen requested changes
Cuando alguno de los campos que no son obligatorios no se llena en el formulario para solicitar ser emprendedor, se ve como null en las solicitudes de emprendedores que puede aceptar el superadmin. Por ejemplo en la captura: 
![image](https://github.com/ciceunicen/web/assets/118905050/2b5077f1-ab68-41fc-b3b2-4a6de5651dd8)

Fijate de revisar los campos no obligatorios y en caso que no se carguen, que aparezca un "-" o algo que denote que no fue aportado.

2024-06-07 18:26 UTC, Renzo-Guerra requested changes
Cuando copiase y pegaste el esquema general de la tabla, copiaste un div que funcionaba como una ventana emergente de error cuando se queria eliminar un usuario, pero que en este caso no tiene funcionalidad alguna.

![image](https://github.com/ciceunicen/web/assets/104610425/593104c0-fbfb-44ab-ba10-0b88634b25cf)

Está en el archivo solicitudesEmprendedores.html, justo despues del body de la linea 16

2024-06-07 20:26 UTC, scianca1 commented
Listo los cambios

2024-06-07 21:12 UTC, ciceunicen approved these changes

2024-06-08 03:05 UTC, Renzo-Guerra approved these changes

2024-06-09 17:17 UTC, merged