Cicedev 248
ciceunicen/web pull request #89
Opened 2024-06-18 21:00 UTC by scianca1

Agregué, arreglé y refactoricé la paginación en todas las páginas posibles con listas. La única página que quedó sin paginar es la que alista usuarios, ya que está mal hecho el pedido de los usuarios.

2024-06-20 13:44 UTC, Renzo-Guerra requested changes
Como administrador, en la seccion de proyectos, si trato de filtrar en los estadios por "Puesta en marcha - Iniciación", por "Formulación de puesta en marcha" o por "Especificación", el paginado muestra 0/0. 



Puse un console.log al recibir la respuesta del back con el paginado, y resulta que viene mal desde backend.
![image](https://github.com/ciceunicen/web/assets/104610425/412b706a-6dde-478f-a6c1-cc2737d44729)

![image](https://github.com/ciceunicen/web/assets/104610425/6671deb1-707b-4300-81da-e7c43c8185c3)

Por si las dudas no te apruebo la parte del front hasta que se solucione el problema del back. 

El resto de testeos me funciono todo:

LISTAR PROYECTOS ELIMINADOS
- Funciona correctamente.

LISTAR EMPRENDEDORES
- Funciona correctamente

LISTAR PROYECTOS
- Eliminar proyectos, se adapta correctamente. 
- Filtrar: 
  - Por Asistencias anda todo correcto.
  - Por Necesidades anda todo correcto.
  - Combinados entre estos (sin seleccionar los que por estadios se buguea) anda todo perfecto.

2024-06-21 15:31 UTC, scianca1 commented
ahi lo arregle, era un -1 que se pasaba nose porque en una funcion aca en el front, ahi anda todo.

2024-06-21 17:21 UTC, Renzo-Guerra approved these changes

2024-06-24 13:18 UTC, ciceunicen approved these changes

2024-06-24 19:52 UTC, merged